name: Release

on:
  workflow_dispatch:
  push:
    branches: [master, main, alpha, beta, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: socialgouv/workflows/actions/semantic-release@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          author-name: BetaBot
          author-email: BetaBot@BetaBot.com
